// Code generated by Icestudio 0.12
// Sun, 27 Apr 2025 19:07:21 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // TODO: edit the module parameters here
 // e.g. localparam constant_value = 1;
 localparam constant_Addr_trigger = 'h0400_0000;
 localparam constant_Freq_ADC = 100000;
 
 // Input/Output
 reg clk_in;
 reg resetn;
 reg sda;
 reg [31:0] addr;
 reg valid;
 reg [31:0] data_in;
 wire scl;
 wire ready;
 wire [31:0] data_out;
 wire test_serdata;
 wire test_i2c_data_ready;
 wire test_I2C_DATA_OUT;
 
 // Module instance
 main #(
  .v269dbc(constant_Addr_trigger),
  .v9c4340(constant_Freq_ADC)
 ) MAIN (
  .v87186f(clk_in),
  .v4dc0ee(resetn),
  .v80923c(sda),
  .v867561(addr),
  .v8859f4(valid),
  .v23504b(data_in),
  .v9127c2(scl),
  .vfe2384(ready),
  .v504d16(data_out),
  .vf73703(test_serdata),
  .va77527(test_i2c_data_ready),
  .v34d6ed(test_I2C_DATA_OUT)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  clk_in = 0;
  resetn = 0;
  sda = 0;
  addr = 0;
  valid = 0;
  data_in = 0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
