// Code generated by Icestudio 0.12
// Sun, 20 Apr 2025 11:12:29 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // TODO: edit the module parameters here
 // e.g. localparam constant_value = 1;
 localparam constant_>= = 1024;
 localparam constant_< = 'h0200_0000;
 localparam constant_< = 1024;
 localparam constant_0 = 'h0200_0008;
 localparam constant_1 = 'h03000000;
 localparam constant_Addr_ADC = 'h0400_0000;
 localparam constant_Freq_ADC = 100000;
 
 // Input/Output
 reg 0;
 reg 1;
 reg 2;
 wire [7:0] LEDS;
 wire 0;
 wire 1;
 wire 2;
 wire 3;
 wire 4;
 wire 5;
 wire 6;
 wire 7;
 
 // Module instance
 main #(
  .vafbbea(constant_>=),
  .v8c97ba(constant_<),
  .v9217e8(constant_<),
  .v9de176(constant_0),
  .v051dbb(constant_1),
  .vb49a23(constant_Addr_ADC),
  .v82bd1d(constant_Freq_ADC)
 ) MAIN (
  .v4922c7(0),
  .vf7cf7d(1),
  .v013906(2),
  .v1e554b(LEDS),
  .vc267e1(0),
  .v7abb98(1),
  .vda2c07(2),
  .v55f1ca(3),
  .ve5de99(4),
  .v97f0aa(5),
  .v5ec250(6),
  .v5100fa(7)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  0 = 0;
  1 = 0;
  2 = 0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
