// Code generated by Icestudio 0.12
// Sun, 27 Apr 2025 17:28:32 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 10;
 
 // TODO: edit the module parameters here
 // e.g. localparam constant_value = 1;
 localparam constant_greaterEqual_flash = 1024;
 localparam constant_lesser_flash = 'h0200_0000;
 localparam constant_lesser_ram = 1024;
 localparam constant_Addr_uart = 'h0200_0008;
 localparam constant_Addr_outport = 'h03000000;
 localparam constant_Addr_ADC = 'h0400_0000;
 localparam constant_Freq_ADC = 100000;
 
 // Input/Output
 reg RX_pin;
 reg MISO_pin;
 wire [7:0] LEDS;
 wire MOSI_PIN;
 wire SCLK_pin;
 wire SS_pin_OUT_PORT;
 wire TX_pin;
 wire SS_pin_FLASH;
 wire SCK_pin;
 wire MOSI_pin;
 wire test;
 
 // Module instance
 main #(
  .vafbbea(constant_greaterEqual_flash),
  .v8c97ba(constant_lesser_flash),
  .v9217e8(constant_lesser_ram),
  .v9de176(constant_Addr_uart),
  .v051dbb(constant_Addr_outport),
  .vb49a23(constant_Addr_ADC),
  .v82bd1d(constant_Freq_ADC)
 ) MAIN (
  .v4922c7(RX_pin),
  .v013906(MISO_pin),
  .v607950(LEDS),
  .v82b9e8(MOSI_PIN),
  .v7abb98(SCLK_pin),
  .vda2c07(SS_pin_OUT_PORT),
  .v55f1ca(TX_pin),
  .v97f0aa(SS_pin_FLASH),
  .v5ec250(SCK_pin),
  .v5100fa(MOSI_pin),
  .vefcf91(test)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  RX_pin = 0;
  MISO_pin = 0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
